export type advertisement = {
  advertisementId: number;
  mainAdvertisementName: string;
  serviceId: number;
  serviceName: string;
  advertiserId: string;
  adminId: string | null;
  adStartDate: string;
  adEndDate: string;
  clicks: number;
  likes: number;
  views: number;
  saved: number;
  shared: number;
  distance: number;
  adStatus: string;
  reviewNotes: string;
  description: string | null;
  detailedDescription: string;
  address: string;
  phoneNumber: string;
  priceRangeLow: number;
  priceRangeHigh: number;
  openingHourStart: string;
  openingHourEnd: string;
  googleMapLink: string;
  websiteLink: string | null;
  deliveryAvailable: string | null;
  averageRating: number | null;
  reviewCount: number | null;
  mediaList: any[];
};
